# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-export

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-export
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: billing-export
    spec:
      serviceAccountName: billing-export
      containers:
        - name: billing-export
          image: dparrish/gke-billing-export:1.0.1
          args: [
            "--config=/etc/gke-billing-export/config.json",
          ]
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/service-key/key.json"
          volumeMounts:
            - name: service-key
              mountPath: "/etc/service-key"
              readOnly: true
            - name: config
              mountPath: "/etc/gke-billing-export"
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 100Mi
      volumes:
        - name: service-key
          secret:
            secretName: billing-export-credentials
        - name: config
          configMap:
            name: billing-export-config
