steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: '/bin/bash'
  args: ['-c', 'gsutil -m cp -r gs://${PROJECT_ID}_cache/.ivy2 /workspace || true']
  id: retrieve-cache
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['-ivy', '/workspace/.ivy2/', 'clean', 'update', 'compile', 'test']
  id: compile-and-test
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['-ivy', '/workspace/.ivy2/', 'pack']
  id: create-package
- name: gcr.io/cloud-builders/gsutil
  entrypoint: '/bin/bash'
  args: ['-c', 'gsutil -m cp -r /workspace/.ivy2 gs://${PROJECT_ID}_cache/ || true']
  id: upload-cache
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_pkgs/kafka2avro/'
    paths: ['target/pack/lib/*.jar']
